// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSFNpyCjofsORCtJbNb2uz8TsJyXPF0cE',
    appId: '1:401737450959:web:fb824d8234ba16021afeba',
    messagingSenderId: '401737450959',
    projectId: 'bill-flow-81cf0',
    authDomain: 'bill-flow-81cf0.firebaseapp.com',
    storageBucket: 'bill-flow-81cf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdE-wxewk_by6ZxqQMGwvFbWkO8e12vSo',
    appId: '1:401737450959:android:6c8024747b7d83151afeba',
    messagingSenderId: '401737450959',
    projectId: 'bill-flow-81cf0',
    storageBucket: 'bill-flow-81cf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdE-wxewk_by6ZxqQMGwvFbWkO8e12vSo',
    appId: '1:401737450959:ios:your-ios-app-id', // Placeholder
    messagingSenderId: '401737450959',
    projectId: 'bill-flow-81cf0',
    storageBucket: 'bill-flow-81cf0.firebasestorage.app',
    iosBundleId: 'com.jarvikktech.BillFlow',
  );
}
